name: CI

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Install required packages. Adjust the list according to your project requirements.
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install rpm
          sudo apt-get install dpkg
      
          wget https://github.com/PySysLink/PySysLinkBase/releases/download/v0.1.0/PySysLinkBase-0.1.0-Linux-x86_64.deb && \
          sudo dpkg -i PySysLinkBase-0.1.0-Linux-x86_64.deb || true 
          
          wget https://github.com/PySysLink/BlockTypesBasicCpp/releases/download/v0.1.0/BlockTypesBasicCpp-0.1.0-Linux-x86_64.deb && \
          sudo dpkg -i BlockTypesBasicCpp-0.1.0-Linux-x86_64.deb || true 
          sudo apt-get install -f -y 



      # Configure the project with tests enabled
      - name: Configure CMake no tests
        run: |
          mkdir build
          cd build
          cmake ..

      # Build the project using make
      - name: Build
        run: |
          cd build
          make
          sudo make install


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BlockTypeSupportsBasicCppSupport-artifacts
          path: |
            build/basic_cpp_support.*.pslkbtsp.yaml
            build/src/libBlockTypeSupportsBasicCppSupport*
    
